/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Editor: typeof import('./../src/components/Editor.vue')['default']
    FileTabs: typeof import('./../src/components/FileTabs.vue')['default']
    FileTree: typeof import('./../src/components/FileTree.vue')['default']
    MainLayout: typeof import('./../src/components/MainLayout.vue')['default']
    Test: typeof import('./../src/components/Test.vue')['default']
  }
}
