/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CodeEditor: typeof import('./../src/components/CodeEditor.vue')['default']
    Extend: typeof import('./../src/components/Extend.vue')['default']
    FileTree: typeof import('./../src/components/FileTree.vue')['default']
    'FileTree.bak': typeof import('./../src/components/FileTree.bak.vue')['default']
    Interactive: typeof import('./../src/components/Interactive.vue')['default']
    MainLayout: typeof import('./../src/components/MainLayout.vue')['default']
    NativeWorkspace: typeof import('./../src/components/NativeWorkspace.vue')['default']
    PalmCodeMirror: typeof import('./../src/components/PalmCodeMirror.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Terminal: typeof import('./../src/components/Terminal.vue')['default']
    WorkspaceEditor: typeof import('./../src/components/WorkspaceEditor.vue')['default']
  }
}
