[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "24.0.0"
anyhow = { workspace = true } 
thiserror = { workspace = true } 
serde = { workspace = true,  features = ["derive"]}
serde_json = { workspace = true}